POST http://127.0.0.1:8080/api/auth/signin HTTP/1.1
content-type: application/json

{
    "email": "admin@gmail.com",
    "password": "123456"
}

###

POST http://127.0.0.1:8080/api/auth/signup HTTP/1.1
content-type: application/json

{
    "email": "customer@gmail.com",
    "password": "123456",
    "role": "ROLE_CUSTOMER"
}

###

GET http://127.0.0.1:8080/api/products
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJhZG1pbkBnbWFpbC5jb20iLCJpYXQiOjE3MDYyMTYyNTEsImV4cCI6MTcwNjMwMjY1MX0.ZDVgP2UIkzYVwaL_WBDVXyIskOfsYzXFRsbbTq9cIHE

###

GET http://127.0.0.1:8080/api/restaurants
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJhZG1pbkBnbWFpbC5jb20iLCJpYXQiOjE3MDYyMTYyNTEsImV4cCI6MTcwNjMwMjY1MX0.ZDVgP2UIkzYVwaL_WBDVXyIskOfsYzXFRsbbTq9cIHE
