GET http://127.0.0.1:8080/products
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJhZG1pbkBnbWFpbC5jb20iLCJpYXQiOjE3MDM1NDE4NzYsImV4cCI6MTcwMzYyODI3Nn0.dcQKYU7YThtjpKPqX2cuTSpzfUq0bypfyG88Ku9cyZM

###

POST http://127.0.0.1:8080/api/auth/signin HTTP/1.1
content-type: application/json

{
    "email": "admin@gmail.com",
    "password": "123456"
}

###

POST http://127.0.0.1:8080/api/auth/signup HTTP/1.1
content-type: application/json

{
    "email": "customer@gmail.com",
    "password": "123456",
    "role": "ROLE_CUSTOMER"
}
